config:
  target: "http://localhost:5173"
  phases:
    - duration: 60
      arrivalRate: 5
      name: "Warm up"
    - duration: 300
      arrivalRate: 10
      name: "Load test"

scenarios:
  - name: "Navigation through all routes"
    weight: 100
    flow:
      # Navigate to home
      - get:
          url: "/"
          
      # Click on Test Routes button
      - get:
          url: "/route1"
          
      # Navigate through all 200 routes
      - get: { url: "/route2" }
      - get: { url: "/route3" }
      - get: { url: "/route4" }
      - get: { url: "/route5" }
      - get: { url: "/route6" }
      - get: { url: "/route7" }
      - get: { url: "/route8" }
      - get: { url: "/route9" }
      - get: { url: "/route10" }
      # ... and so on for routes 11-200
      # Add more routes as needed for your test

