config:
  target: "http://localhost:5174"
  phases:
    - duration: 60
      arrivalRate: 5
      name: "Warm up"
    - duration: 300
      arrivalRate: 10
      name: "Load test"

scenarios:
  - name: "Navigation through all routes"
    weight: 100
    flow:
      # Navigate to home
      - get:
          url: "/"
          
      # Click on Test Routes button
      - get:
          url: "/route1"
          
      # Navigate through all 200 routes (sample)
      - get: { url: "/route2" }
      - get: { url: "/route3" }
      - get: { url: "/route4" }
      - get: { url: "/route5" }
      # ... add more routes as needed
